#!/bin/bash

dIFS=$IFS
IFS=$'\n'  # so that the following for loop splits input just on newlines rather than all whitespace

REGEX="^([[:digit:]]{1,3})\,\ (http[0-9A-Za-z\:\/\.\_\-]+)"
  
for T in `cat video-list.txt`; do
  if [[ $T =~ $REGEX ]]; then 
    sqlite3 ecalprog.db "UPDATE talks SET videourl='"${BASH_REMATCH[2]}"' WHERE id="${BASH_REMATCH[1]}
  fi
done
